server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/box_shop?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456





